### ISSUE TITLE
After running inference, predictions all appear on video index 1 instead of respective videos

### ISSUE THREAD

**Issue by sophiaanner** [talmolab/sleap#2442]
# Bug description

When running inference on multiple videos in a project and then merging the prediction files back into the main project, all predictions are incorrectly assigned to video index 1, regardless of which video they were actually generated from. I also reported this issue in the help discussion: #2437 

## Expected behaviour

When merging prediction files into the main project, each prediction file should be assigned to its corresponding original video based on the video reference stored in the prediction file. For example:
- Predictions generated from video index 0 should appear on video index 0
- Predictions generated from video index 24 should appear on video index 24
- etc.

## Actual behaviour

Predictions for video index 0 are correctly assigned to video index 0. All remaining predictions from the additional 32 videos are consolidated and assigned to video index 1 in the main project, regardless of which video they were originally generated from. This occurs both when:
1. Using the GUI to run inference on "random frames (660 frames)" and the results that automatically load following inference
2. Manually merging individual prediction files using File → Merge Data From...

Notably, when opening individual prediction files directly (without merging), they correctly display their associated video with matching file paths.

## Your personal set up

-   OS: Windows 11 Pro
-   Version(s): SLEAP 1.5.1; python 3.11 
-   SLEAP installation method: uv tool install (needed to specify --python 3.11 because it wasn't working with 3.14). 
-  GPU: NVIDIA RTX PRO 500 Blackwell Generation Laptop GPU (CUDA 12.8)

## Environment packages

Using Python 3.14.0 environment at: AppData\Roaming\uv\python\cpython-3.14.0-windows-x86_64-none

## Logs

Command line output from opening SLEAP and running inference on random frames. 
```
C:\Users\sophi>uv run sleap-label
Saving config: C:\Users\sophi\.sleap\1.5.1\preferences.yaml
Restoring GUI state...

Software versions:
SLEAP: 1.5.1
Numpy: 2.3.3
Python: 3.11.14
OS: Windows-10-10.0.26100-SP0

Happy SLEAPing! :)
Error occurred during callback 0 for palette!
[<function MainWindow._create_menus.<locals>.add_submenu_choices.<locals>.<lambda> at 0x000002723BF04720>, <function MainWindow._load_overlays.<locals>.overlay_state_connect.<locals>.<lambda> at 0x000002723BFB8180>, <bound method MainWindow.plotFrame of <sleap.gui.app.MainWindow(0x2727f7203f0) at 0x000002723B93F340>>, <function MainWindow._load_overlays.<locals>.<lambda> at 0x000002723BFB8360>, <function MainWindow._load_overlays.<locals>.<lambda> at 0x000002723BFB8400>, <function MainWindow._load_overlays.<locals>.overlay_state_connect.<locals>.<lambda> at 0x000002723BFB8CC0>, <bound method MainWindow.plotFrame of <sleap.gui.app.MainWindow(0x2727f7203f0) at 0x000002723B93F340>>, <function MainWindow._load_overlays.<locals>.<lambda> at 0x000002723BFB8EA0>, <function MainWindow._load_overlays.<locals>.<lambda> at 0x000002723BFB8F40>]
'PySide6.QtWidgets.QGraphicsDropShadowEffect' object has no attribute 'text'
Error occurred during callback 0 for distinctly_color!
[<function MainWindow._create_menus.<locals>.add_submenu_choices.<locals>.<lambda> at 0x000002723BF04A40>, <function MainWindow._load_overlays.<locals>.overlay_state_connect.<locals>.<lambda> at 0x000002723BFB8220>, <bound method MainWindow.plotFrame of <sleap.gui.app.MainWindow(0x2727f7203f0) at 0x000002723B93F340>>, <function MainWindow._load_overlays.<locals>.<lambda> at 0x000002723BFB84A0>, <function MainWindow._load_overlays.<locals>.overlay_state_connect.<locals>.<lambda> at 0x000002723BFB8D60>, <bound method MainWindow.plotFrame of <sleap.gui.app.MainWindow(0x2727f7203f0) at 0x000002723B93F340>>, <function MainWindow._load_overlays.<locals>.<lambda> at 0x000002723BFB8FE0>]
'PySide6.QtWidgets.QGraphicsDropShadowEffect' object has no attribute 'text'
Using already trained model for centroid: C:/Users/sophi/OneDrive/Desktop\models\251024_170913.centroid.n=53\training_config.yaml
Using already trained model for centered_instance: C:/Users/sophi/OneDrive/Desktop\models\251024_182813.centered_instance.n=53\training_config.yaml
Command line call:
sleap-nn-track --data_path C:/Users/sophi/OneDrive/Desktop/20251014_MergedProj.slp --video_index 0 --frames 1724,7985,11124,13303,13445,14271,15810,16224,18561,23980,24650,26792,27721,28036,28730,32681,32971,35343,40480,40891 --model_paths C:\Users\sophi\OneDrive\Desktop\models\251024_170913.centroid.n=53 --model_paths C:\Users\sophi\OneDrive\Desktop\models\251024_182813.centered_instance.n=53 -o C:/Users/sophi/OneDrive/Desktop\predictions\20251014_MergedProj.slp.251025_114739.predictions.slp --batch_size 8

2025-10-25 11:47:51 | INFO | sleap_nn.predict:run_inference:319 | Started inference at: 2025-10-25 11:47:51.056182
2025-10-25 11:47:51 | INFO | sleap_nn.predict:run_inference:335 | Using device: cuda
Predicting... ---------------------------------------- 100% 20/20 ETA: 0:00:00 Elapsed: 0:00:07 16.7 FPS
2025-10-25 11:47:59 | INFO | sleap_nn.predict:run_inference:453 | Finished inference at: 2025-10-25 11:47:59.431260
2025-10-25 11:47:59 | INFO | sleap_nn.predict:run_inference:454 | Total runtime: 8.375077724456787 secs
2025-10-25 11:47:59 | INFO | sleap_nn.predict:run_inference:465 | Predictions output path: C:/Users/sophi/OneDrive/Desktop\predictions\20251014_MergedProj.slp.251025_114739.predictions.slp
2025-10-25 11:47:59 | INFO | sleap_nn.predict:run_inference:466 | Saved file at: 2025-10-25 11:47:59.601670

Process return code: 0
Command line call:
sleap-nn-track --data_path C:/Users/sophi/OneDrive/Desktop/20251014_MergedProj.slp --video_index 1 --frames 4517,5380,7273,8913,14661,19312,19716,21523,21813,22742,23073,23976,29757,30752,32610,33260,40459,41626,41984,42010 --model_paths C:\Users\sophi\OneDrive\Desktop\models\251024_170913.centroid.n=53 --model_paths C:\Users\sophi\OneDrive\Desktop\models\251024_182813.centered_instance.n=53 -o C:/Users/sophi/OneDrive/Desktop\predictions\20251014_MergedProj.slp.251025_114800.predictions.slp --batch_size 8

2025-10-25 11:48:06 | INFO | sleap_nn.predict:run_inference:319 | Started inference at: 2025-10-25 11:48:06.803961
2025-10-25 11:48:06 | INFO | sleap_nn.predict:run_inference:335 | Using device: cuda
Predicting... ---------------------------------------- 100% 20/20 ETA: 0:00:00 Elapsed: 0:00:02 12.2 FPS
2025-10-25 11:48:10 | INFO | sleap_nn.predict:run_inference:453 | Finished inference at: 2025-10-25 11:48:10.420145
2025-10-25 11:48:10 | INFO | sleap_nn.predict:run_inference:454 | Total runtime: 3.6161839962005615 secs
2025-10-25 11:48:10 | INFO | sleap_nn.predict:run_inference:465 | Predictions output path: C:/Users/sophi/OneDrive/Desktop\predictions\20251014_MergedProj.slp.251025_114800.predictions.slp
2025-10-25 11:48:10 | INFO | sleap_nn.predict:run_inference:466 | Saved file at: 2025-10-25 11:48:10.588981
```

This process was repeated for all 33 videos (indices 0-32), each creating a separate prediction file.

## Screenshots

Video index 0 (first video listed) that has predictions properly assigned for 20 random frames. 
<img width="1920" height="1128" alt="Image" src="https://github.com/user-attachments/assets/6fd9ffbb-7d59-4112-ac3a-123c9a64d1e8" />

Video index 1 (second video listed) that has predictions for 20 random frames in this video AND for video indices 2-32. You can see the predicted locations of the flies do not line up with the flies in this video.

<img width="1920" height="1128" alt="Image" src="https://github.com/user-attachments/assets/4139e739-01e4-4258-a964-363ae2220060" />

Video index 2 which has no predictions (because they were put onto video index 1)

<img width="1920" height="1128" alt="Image" src="https://github.com/user-attachments/assets/ee1328b3-e3df-46d0-b187-2b1e295bede7" />

When I open one of the prediction files on its own, it is correctly linked to the proper video. The filepath are the same here as in the main project.

<img width="1920" height="1128" alt="Image" src="https://github.com/user-attachments/assets/684ab8f9-ef89-474d-9052-bbebef2e50d2" />

## How to reproduce

1. Open project in SLEAP GUI
2. Go to Predict → Run Inference...
3. Select "Random frames" under "Predict on:"
4. Run inference with trained models

**Comment by ElTinmar** [comment]
Hi sophiaanner! 

This is probably the same as this issue:
https://github.com/talmolab/sleap-io/issues/255

A quick fix while they fix this properly could be to patch your local version of sleap:

https://github.com/talmolab/sleap-io/issues/255#issuecomment-3413131656

**Comment by sophiaanner** [comment]
Hi @ElTinmar!

Thanks for connecting me with this fix! I was able to make your suggested adjustment in within the labels.py file. Since I installed with uv tool, for me this was in User\AppData\Roaming\uv\tools\sleap\Lib\site-packages\sleap_io\model.
