### ISSUE TITLE
GUI crash: VideosTableModel.item_to_data dereferences a None video backend (AttributeError: 'NoneType' object has no attribute 'filename')

### ISSUE THREAD

**Issue by tom21100227** [talmolab/sleap#2798]
## Summary

The GUI videos table crashes with `AttributeError: 'NoneType' object has no attribute 'filename'` whenever a `Video` in `labels.videos` has `backend is None`. `VideosTableModel.item_to_data` reassigns `item` to the video's backend and then dereferences `item.filename` with no guard for the backend being `None`.

A `Video` ends up with `backend is None` whenever its file is **momentarily inaccessible at open time** (a file lock, AV scan, Windows indexing, a slow/flaky drive, or a still-flushing large recording). This commonly surfaces during the **post-training table refresh** in the active-learning loop — training/inference has just touched the video, and the refresh re-evaluates the backend.

Reported in #2794 (active-learning workflow, training round n=101). Repro'd exactly against the uploaded data.

This is the same failure family as #2742 / PR #2743, **one line further down**: PR #2743 guarded the `img_shape` frame read but not the `item.filename` access, so a *fully* `None` backend still crashes. **Still present on `develop` (1.6.3).**

## Reported traceback (#2794)

```
Finished training centered_instance.
Traceback (most recent call last):
  File "...\site-packages\sleap\gui\dataviews.py", line 409, in item_to_data
    if isinstance(item.filename, str)
AttributeError: 'NoneType' object has no attribute 'filename'
```

## How it fails (the code path)

`sleap/gui/dataviews.py` → `VideosTableModel.item_to_data` (develop @ 1.6.3, lines 481–516):

```python
def item_to_data(self, obj, item: "VideoBackend"):
    data = {}
    if isinstance(item, Video):
        item = item.backend          # (1) -> None when the backend failed to open

    try:
        img_shape = item.img_shape   # (2) None.img_shape raises, but PR #2743 catches it
    except Exception:
        img_shape = None

    for property in self.properties:
        if property == "name":
            data[property] = (
                Path(item.filename).name      # (3) None.filename -> AttributeError (UNGUARDED)
                if isinstance(item.filename, str)
                else item.filename[0]
            )
        ...
```

1. `item` (a `sleap_io.Video`) is replaced by `item.backend`, which is `None`.
2. The `img_shape` read raises `AttributeError`, but that's swallowed by the `try/except` added in PR #2743 (#2742) — so the table does *not* blank here.
3. Execution continues to the `name`/`filepath` branches, which call `item.filename` on the `None` backend → **`AttributeError: 'NoneType' object has no attribute 'filename'`**, uncaught → the GUI crashes.

(If a bare `None` were ever in `labels.videos`, the `isinstance(item, Video)` check is skipped and `item.filename` fails identically — same crash site.)

## Why it fails (root cause)

`sleap_io.Video` opens its backend lazily and **only if the file currently exists/opens**:

```python
# sleap_io/model/video.py
backend: VideoBackend | None = None
open_backend: bool = True

def __attrs_post_init__(self):
    if self.open_backend and self.backend is None and self.exists():
        try:
            self.open()
        except Exception:
            pass   # leave backend=None rather than block Video construction
```

`Video.exists()` → `is_file_accessible()`, which is a **real one-byte disk read**:

```python
# sleap_io/io/utils.py
def is_file_accessible(filename) -> bool:
    try:
        with open(filename, "rb") as f:
            f.read(1)
        return True
    except (FileNotFoundError, PermissionError, OSError, ValueError):
        return False
```

So if the file is locked / mid-write / on a flaky drive / temporarily unreadable, `exists()` returns `False`, the backend is never opened (or `.open()` raises and is swallowed), and the `Video` is left with `backend is None` — while still retaining `filename` and `backend_metadata["shape"]`. The videos-table renderer assumes an open backend and crashes.

**Why it's intermittent** (e.g. survives several training rounds, then crashes on one): file accessibility is a real I/O probe that can transiently fail. PR #2743's own comment already notes "intermittent" frame-read failures — this is the unguarded sibling of that case.

## Minimal reproduction (no GUI / no Qt needed)

```python
import sleap_io as sio
from pathlib import Path

# A Video whose file is inaccessible at open time keeps backend=None
# but retains filename + shape metadata.
v = sio.Video(
    filename="D:/does/not/exist/1-doi1.mp4",
    backend_metadata={"shape": [9746, 1080, 1920, 1], "type": "MediaVideo"},
)
assert v.exists() is False and v.backend is None

# Exactly what VideosTableModel.item_to_data does:
item = v
if isinstance(item, sio.Video):
    item = item.backend          # -> None
Path(item.filename)              # AttributeError: 'NoneType' object has no attribute 'filename'
```

Verified with `sleap-io==0.8.0`. Loading the reporter's `labels.v005.slp` and forcing `exists()==False` reproduces the #2794 traceback verbatim.

## Not the cause: non-ASCII video path

The reporter's video lives at `D:/obs-studio/行为学/5.23doi矿场/1-doi1.mp4`. The Chinese path is **not** the bug:
- `is_file_accessible` uses Python `open()`, which is Unicode-safe on Windows.
- sleap-nn read frames from that exact path during eval (`metrics.val.0.npz → distance_metrics.video_paths`).
- sleap-io opens a local copy of the same file fine.

(An ASCII project path is still a reasonable belt-and-suspenders suggestion, but it does not fix this.)

## Secondary symptom in #2794 ("new model not visible in training-config list")

Downstream of the crash, not a separate bug. `ConfigFileInfo.has_trained_model` only checks for `best.ckpt`/`best_model.h5` in the model dir (present for the n=101 run). The crash aborted the post-training UI refresh, so the trained-models list never updated. Restarting SLEAP / reopening the dialog surfaces the model.

## Affected versions

- The `isinstance(item.filename, str)` rendering was introduced in #2052.
- The `img_shape` `try/except` was added in #2743 (#2742) but does **not** cover the `None`-backend `item.filename` access.
- Confirmed present on `develop` @ `1.6.3`. Reporter hit it on a `uv tool install sleap` release (traceback at their `dataviews.py:409`).

## Proposed fix

In `VideosTableModel.item_to_data`, capture the `Video` before reassigning to its backend, and when `backend is None`, render the row from the `Video`'s own `filename` and `backend_metadata["shape"]` (`[frames, H, W, C]`) instead of dereferencing the backend. This extends the #2742/#2743 hardening so a transiently-unreadable video shows a best-effort row (path + cached shape, `?` placeholders) rather than crashing the GUI.

Validated against the uploaded data: with `backend is None`, the fixed path renders
`{name: '1-doi1.mp4', filepath: 'D:/obs-studio/行为学/5.23doi矿场', frames: 9746, height: 1080, width: 1920, channels: 1}`.

## Impact

GUI crash (data-loss-adjacent UX) at the end of a training round in the standard active-learning loop; the user's models and labels are intact on disk but the session is interrupted and the new model appears "missing." Reproducible whenever the source video is momentarily inaccessible during a table refresh.
